### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys#10]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar el logo de pagina al lado de nombre.

## Resultado actual

• No hay ningun logo.

## Captura

![image](https://github.com/FranprzDev/EduSys/assets/53904695/3efed53e-bd92-4681-b193-c54e5f237647)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FranprzDev** [comment]
Hola ya agregué el logo.
