### ISSUE TITLE
Modal error

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys#11]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario admin.
3. Quise crear nuevos usuarios administradores.

## Resultado esperado

• Que el modal muestre información alguna del error.

## Resultado actual

• El modal esta vacio no muestra ningun tipo de informacion alguna.

## Captura

![image](https://github.com/FranprzDev/EduSys/assets/53904695/54f1d1a3-985e-4f54-a432-45d1d1368b9e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FranprzDev** [comment]
No entiendo bien el proceso, ¿Cuándo sucede?
Por las dudas capaz que tiene que ver con el primer Issue, si es el que tira el error cuando se crea un administrador y los datos no están correctos, ya está corregido.
