### ISSUE TITLE
Formulario de contacto

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys#4]
## Proceso

1. Ingrese a la pagina.
2. Llene el formulario de contacto. 

## Resultado esperado

• Que no se permitan números y signos donde va el nombre del usuario.
• Encontrar un max de caracteres donde va el mensaje de la consulta.

## Resultado actual

• Se permiten colocar números y signos donde va el nombre.
• No hay un max de caracteres donde va el mensaje de la consulta.

## Captura

![image](https://github.com/FranprzDev/EduSys/assets/53904695/12a8d350-a7af-4f80-8cbd-c04189daac93)
![image](https://github.com/FranprzDev/EduSys/assets/53904695/634e085a-d6f6-4716-9051-5befbe7b6733)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Buenas! Chicos tendrían por ahí algún usuario registrado o cuanta admin que me pasen para poder continuar con la devolución del proyecto?

**Comment by FranprzDev** [comment]
Sí, te lo paso.
Usuario : Contraseña
SuperAdministrador -> admin@gmail.com : Adm1n@RC
Administrador -> test5@gmail.com : Adm1n@RCD

**Comment by FranprzDev** [comment]
Hola Nico! Límite el máximo del comentario a 200 caracteres.
También ya valide lo que me pediste aquí.

**Comment by Nidev-lab** [comment]
Hoa Francisco, como estas? Estuve viendo y aun persiste un pequeño detalle, si te fijas al momento de poner un nombre valido no me deja enviar la consulta, pero si pongo una sola letra si me lo toma y me deja enviar la consulta, te adjunto imagenes
![image](https://github.com/FranprzDev/EduSys/assets/53904695/41c37318-6bd6-44a8-b0bc-1bb302823cd8)
![image](https://github.com/FranprzDev/EduSys/assets/53904695/a9e6f506-a935-4552-8b13-21f79b44a97f)
![image](https://github.com/FranprzDev/EduSys/assets/53904695/d0b1090f-4a92-4c11-a040-5c2d2d914cfe)

**Comment by FranprzDev** [comment]
Hola Nico, ahí creo que ya estaría listo el error.
