### ISSUE TITLE
Boton sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys#6]
## Proceso

1. Ingrese a la pagina.
2. Me loguee como admin.
3. Quise registrar un nuevo user admin,

## Resultado esperado

• Que al ingresar los datos solicitados en el formulario se pueda crear un nuevo usuario administrador.

## Resultado actual

• Al completar con todos los datos el boton "Guardar cambios" no cumple ninguna accion.

## Captura

![image](https://github.com/FranprzDev/EduSys/assets/53904695/d6688ae0-c0dc-40a3-974e-3efe72f33905)
PD: Validen el form para que no se puedan colocar numeros ni signos donde van los nombres. 

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Hola buenas! Déjame un comentario así lo reviso y si esta todo ok lo cierro yo.

**Comment by Nidev-lab** [comment]
Status: Al completar con todos los datos solicitados al momento de darle al boton para crear un nuevo usuario administrador
me sale error
Capturas:
![image](https://github.com/FranprzDev/EduSys/assets/53904695/d26dcd17-a803-45aa-9ffc-095a978508ed)

![image](https://github.com/FranprzDev/EduSys/assets/53904695/d75ab796-cc8b-4324-beaf-73329da819e6)
(Errores de consola)
![image](https://github.com/FranprzDev/EduSys/assets/53904695/7496fff4-55d1-4632-a8c2-4f01be23a0b8)

**Comment by FranprzDev** [comment]
Hola! Es por que el sistema ya está asumiendo que es enfocado a Tucumán se incluye el prefijo (381) y eso está tirando el error en el backend.
¿A eso lo pongo en un label como el de contraseña?
Ayer cuando lo estaba corrigiendo no estaba seguro si ponerlo,
Si no me equivoco, es básicamente eso.
De todos modos, me dices bien si pongo el label pero ese modal debería abrir un error con el mensaje que trae el backend; que raro que no lo traiga, ya intentaré recrear las condiciones.
De todos modos sugiero algunas contraseñas, capaz que eso pueda generar problemas
Adm1n@RC
Usu4ar1o@RC

**Comment by Nidev-lab** [comment]
Buenas! Si ponle un label de contraseña y vemos que onda.

**Comment by FranprzDev** [comment]
Hola, corregido.

**Comment by Nidev-lab** [comment]
Buenas! Estuve viendo y el error continua, revísalo si podes por favor.

**Comment by FranprzDev** [comment]
Tengo entendido que ya estaba corregido, te paso una captura.
![image](https://github.com/FranprzDev/EduSys/assets/112534083/7c64cc6d-8e09-4bad-8162-07861f8238cd)

Esto si me los crea aquí en el listado.
![image](https://github.com/FranprzDev/EduSys/assets/112534083/a02928e4-e88f-4f74-9994-fd8854273275)

En todo caso, ahí modifique el modal y ahora si da un aviso de cuales son los datos incorrectos.
