### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys#8]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.

## Resultado esperado

• Que al hacer click los botones generen una acción.

## Resultado actual

• Los botones no cumplen ninguna funcion.

## Captura

![image](https://github.com/FranprzDev/EduSys/assets/53904695/b09c608e-8aa0-4c11-9758-6ae4244f286a)
PD: el boton de logout funciona correctamente

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FranprzDev** [comment]
Hola, ya funcionan los botones.
La institución si bien era un requerimiento, era un requerimiento opcional que podríamos o no agregar.
Más allá de eso, nosotros hicimos la institución que se pueda crear una sola vez,  y ya está creada en la base de datos.
![image](https://github.com/FranprzDev/EduSys/assets/112534083/7ba9a3b9-3135-4aee-9974-6d915f4ea756)
La idea del popover de la Institución es básicamente mostrar sobre la institución que se está trabajando.
Si quieres la puedo eliminar así lo pruebes, no te salió para generar una nueva institución por que ya estaba creada con anterioridad.

**Comment by Nidev-lab** [comment]
Ah genial , de ser así te recomiendo que eliminen este modal que se abre cuando se actualiza la pagina, al loguearme con un user admin al actualizar la pagina aparece por unos segundos.
![image](https://github.com/FranprzDev/EduSys/assets/53904695/277d6762-dbe5-43c3-b09f-a997eca9948d)

**Comment by FranprzDev** [comment]
Hola! Solucionado.
