### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Nidev-lab** [FranprzDev/EduSys#9]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que los botones del footer funcionen de la misma manera cuando estoy logueado y cuando no.

## Resultado actual

• Al no estar logueado lo botones del footer redirigen a un 404, pero cuando estoy logueado con un user admin los botones del footer se rompen y redirigen todos al mismo site.

## Captura

Logueado

https://github.com/FranprzDev/EduSys/assets/53904695/25c15bcb-79f6-4e8b-8f28-b3c556b2a765

No Logueado

https://github.com/FranprzDev/EduSys/assets/53904695/8fa5b9d8-d087-4207-8e3f-6f9574dfb250

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by FranprzDev** [comment]
Hola, ya fue resuelto este problema.

**Comment by Nidev-lab** [comment]
Perfecto! Eso es todo, felicidades!
